---
title: "Blog Service Message about syndication with DZONE and JCG" 
layout: posta
comments: on
---

I have contracted link:http://www.dzone.com/[DZONE] and equally link:http://www.javacodegeeks.com/[Java Code Geeks] as syndication partners. They started to select my articles for republishing on their sites.

The cooperation between me and the syndication partners is non-profit and I truly believe that this is mutually benefiting all parties including the syndication partners as well as you, the reader. Cooperation with syndication partners will hopefully increase the number of people using the blog and belonging to a larger technical community is an advantage.

Feel free to visit these sites and use the services, read articles, express your point of view in forms of comments, whatever you feel appropriate.

=== Comments imported from Wordpress


*lukaseder* 2014-02-24 13:33:33





[quote]
____
I've made a great experience with both syndication partners myself, so thumbs up to this step forward for your blog!
____



