---
title: Hidden Classes in Java 15
layout: posta
comments: on
---


== 1. Introduction







Java can have anonymous classes from the very start.
However, anonymous classes were not really anonymous.
You did not need to name them, but under the hood they were named by the Java compiler.
If you are familiar with the command `javap` you can "disassemble" a JAR file, and you can see the name the compiler generated for the anonymous classes.

Java 15 introduced hidden classes, which really do not have name.
Almost, as you will see.
It is not part of the language, but part of the JDK.
There is no language element to create a hidden classes, but there are JDK methods and classes that come to rescue.

In this article we will discuss

* what hidden classes are and what is the reason to have them,

* how you can use hidden classes,

* how to load hidden classes using the JDK methods and finally

* how to create and load hidden classes the easy way using link:https://github.com/sourcebuddy/sourcebuddy[SourceBuddy].

[NOTE]
====
I created SourceBuddy, and it is an Apache v2.0 licensed open source program.
During the creation of the code I have learned a few things about hidden classes I wanted to share with you.
You may also look at this article as SourceBuddy promotion, which is ok if you do that.
Nevertheless, I hope being successful adding extra value in this article.
====

== 2. What are hidden classes?

There is an easy to read link:https://www.baeldung.com/java-hidden-classes[introductory article] about hidden classes on Baeldung.
If you are impatient and do not care some intricate details, just go there and read that article.
Baeldung articles are always short, focusing on the most important and correct.
They give a good starting point, which there would be no reason to repeat.

Hidden classes were proposed in the link:https://openjdk.org/jeps/371[JEP371], and it reads:

____
hidden ... classes that cannot be used directly by the bytecode of other classes
____

This is a bit short and may not be easy to understand what it really means.

A hidden class is loaded into the JVM.
When a class is in source code format or byte code it cannot be "hidden".
This term can refer only to loaded classes.
Calling them secretly loaded class could be more appropriate.

A class gets secret when it is loaded in a special way so that it remains secret in front of other code parts.
Remaining secret, however, does not mean that other codes cannot use this class.
They can so long as long they "know" about the secret.
The big difference is that this class is not "advertised" in the sense that it cannot be found by the name.

When you load a class the hidden way creating a hidden class you will have a reference to this class.
Using the reflective methods you can instantiate the class many times, and then you can invoke methods, set, get fields.
If the class implements an interface or extends a class you can cast the instance reference to the interface and class and invoke the methods without reflection.

The class is hidden for two reasons:

* it does not have a name other classes could reference, and

* there is no reference from the class loader to the class.

When you call `getName()` or `getSimpleName()` on a variable referencing a hidden class you will get some string.
These are names for messages, for humans and are irrelevant for the other classes.
When a class refers to another class it needs the canonical name.
`getCanonicalName()` returns `null`.
Canonical name is the real name of the class, and that is non-existent in the case of hidden classes.

Since the class cannot be found through the class loader without the canonical name, there is no reason for the loader to keep a reference to the class.
Why would it keep a reference when it cannot give the class to anyone.
Keeping a reference woult have only one side effect: it would prevent the GC to unload the class so long as long the class loader is alive.

Since there is no reference from the class loader to the class the GC can unload the class object as soon as it is out of use.

== 3. What is the use of hidden classes?

The link:https://openjdk.org/jeps/371[JEP371] describes the reason for hidden classes.
It says

____
Allow frameworks to define classes as non-discoverable implementation details of the framework, so that they cannot be linked against by other classes nor discovered through reflection.
____

Many frameworks use dynamically created classes.
They are proxy classes in most of the cases.
A proxy class implements an interface or extends another class and when invoked it calls an instance of the interface or the original class.
It also does something extra as well usually, or else there would be no reason for the proxy class and proxy instance.

An example is the Spring framework when your code requires it to inject a request bean into a session bean.
(Or any other shorter lifecycle bean into a longer one.)
There can be several threads serving different requests at the same time all belonging to the same session.
All these threads will see the same session bean, but they magically will see their own request beans.
The magic is a proxy object extending the request bean's class.
When you call a method on the request bean, you invoke the proxy instance.
It checks the thread and the request that it serves and forwards the call to the appropriate request bean.

Another example is JPA lazy loading.
You can have an SQL table where each row references the previous one.
When you try to load the last record it will automatically load the previous one, which in deed will load the one before and so on.
It will load the whole table.
This happens unless you annotate the field as lazy.
It means that the actual data from the database has to be loaded only when it is needed.

When you load the record you get a proxy object.
This proxy object knows which record it refers to and will load the record from the database only when a method is called.

The same mechanism is used for Aspect Oriented Programming and in many other cases.

You can create a proxy class using only the JDK reflection API so long as long the target class implements the interface you want to proxy.
If there is no such interface you can use the link:https://bytebuddy.net/[ByteBuddy] library.

[NOTE]
====
The link:https://github.com/cglib/cglib[cglib] library is widely used and well-known in the many frameworks, but it is deprecated recently.
====

When you create such classes you do not need any name for these classes.
You get the reference to the class and the reference to the instance.
The framework injects the reference to the field it has to and then the code uses them as any object.
It does not need to know the name of the class.
All it needs to know that it is an instance of the target class or interface.
However, some code may discover the name.
These classes have some name that reflection can discover.
Some "clever" junior may discover it and play some neat trick, that you may have later issues maintaining.
Would it be better if there was no name at all?
Probably yes, it would be cleaner.
Hence: hidden classes.

[NOTE]
====
Thes proxy classes may also cause some issue when you implement the `equals(Object other)` method.
The usual implementation of the link:https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/lang/Object.html#equals(java.lang.Object)[equals] method starts comparing the `other` object's class to the actual class.
It will eventually be `false` when the other object is a proxy instance.
What the `equals()` method should check is the assignability whenever there is a possibility that the `other` object is a proxy.
====

____
Support extending an access control nest with non-discoverable classes.
____

This is the second bullet point in the list of goals in the link:https://openjdk.org/jeps/371[JEP371].
Hidden classes can be loaded in a way that they become member of a nest.
What is a nest?

[NOTE]
====
If you know what a nesting host is, and you are impatient, jump to the next
____
quote.
____
====

Well it is a long story, but since it is Christmas-time, I am on holiday and this article will not be printed on paper wasting tree, here it goes.
Once upon a time, there was a Java version 1.0 that did not have inner classes.
Now, if you ask me what inner classes are, then you better stop reading it here.
Then Java version 1.1 introduced inner classes, but it did not change the JVM structure.
The JVM did not know anything about inner classes.
The Java compiler created regular (almost) top level classes from the inner classes.
It invented some funny name, like `A$B` when there was a class `B` inside `A`.

NOTE: You can try to define an `A$B` top level class in the same package where the class `A` containing the class `B` is.
`A$B` is an absolutely valid name.
You will see what the compiler does.

There were some hacking with the visibility though.
An inner class has the same visibility as the top level class.
Anything private inside one compilation unit (file) is visible.
Visibility, however, also enforced by the JVM.
But the JVM sees two top level classes.
To overcome this the compiler generated bridge methods in the classes wherever it was needed.
They are package level for the JVM and when called they pass on the call to the private method.

Then came Java 11 something like 25 years later and link:https://openjdk.org/jeps/181[introduced the nest control].
Since Java 11 every class has a relation to another class or to itself, which is the nest host of the class.
Classes having the same nest host can see each other's private members.
The JVM does not need the bridge methods anymore.

When you load a class hidden you can specify it to become the member of the same nest (having the same nest host) as the class that created the lookup object.

NOTE: We have not discussed yet what a lookup object is, and how to load a class hidden.
It will come.
As for now: a lookup object is something that can load a byte array as hidden class into the JVM memory.
When a lookup object is created from inside a method of a class the lookup object will belong to that class.
When a class is loaded as hidden using the lookup object it is possible to pass an option to make the new hidden class to belong to the nest the lookup object was created in.

Without the hidden class functionality I do not know any other possibility to load a class that will belong to an already existing nest.
If you know any possibility, write it in a comment.

The next bullet point reads:
____
Support aggressive unloading of non-discoverable classes, so that frameworks have the flexibility to define as many as they need.
____

It is an important point.
When you create a class it remains in the memory so long as long the classloader is alive.
Classloaders keep references to all the classes they loaded.
These references say that there may be some code asking the classloader to return the loaded class object by the name.
The class may be long forgotten by the application logic, nobody will ever need it.
Still the garbage collector cannot collect it because there is a reference in the classloader.
A solution is to create a new class loader for every new non-hidden dynamically created class, but that is an overkill.

Classloaders loading hidden classes do not keep a reference to the hidden class by default.
As with the nesting host, it is possible to provide an option to differ.

I do not see any reason.
There is no name, not discoverable, but keep an extra reference so the GC cannot throw it away.
If you see any reasonable use case, again: comment.

____
Deprecate the non-standard API sun.misc.Unsafe::defineAnonymousClass, with the intent to deprecate it for removal in a future release.
____

Very well.
Yes.
Absolutely.
Separate articles and many of them.

____
Do not change the Java programming language in any way.
____

Nice point. Sure.

With these we discussed what hidden classes are.
You should have a firm understanding about their nature and why they are important.
We also derailed a bit to nest hosting or host nesting, nesting hosting... whatever.
Hope it was some value.

In the following I will discuss how we create hidden classes using the JDK API and then using link:https://github.com/sourcebuddy/sourcebuddy[SourceBuddy].

== 4. Creating Hidden Classes

Articles and tutorials showing how to load hidden classes use precompiled Java classes.
These are usually part of the running application.
The tutorial calculates the path to the `.class` file and reads the byte code.

Technically this is correct, but it is against the basic need for hidden class loading: load dynamically created classes hidden.
These classes are not hidden.

[NOTE]
====
To explain a bit what I mean by that here is an old story from 1995 describing a similar situation.

In 1995 internet was mainly dial-up and ADSL higher speed internet was an exception.
The fastest speed was 56kbps, which is 1000 times slower than what you get today even on mobile.
I was working for Digital Equipment Corp. in Hungary, and they had a by-the-time-new technology: internet over TV cable.
We installed it as a pilot and made a demo for the journalists.
To demonstrate the high speed we delivered a video on the internet connection.

Journalist understanding and question was:

____
You delivered video using some new technology over a TV cable.
What is the point?
____

Technically it was a good choice to use a video stream as a demonstration.
For the specific audience, it was not the best choice.
====

In this article we will create a class from text, Java source on the fly and then load the resulting byte code as hidden class.


[%collapsible,title=Code Sample Disclaimer, sidebar]
====
[sidebar]
The code samples are available on GitHub in the link:https://github.com/javax0/javax0.github.io/tree/master/_projects[project directory].
Each article has a project directory named `YYYY-MM-DD-article-title` where the project code files are.
The samples are automatically copied from the project directory to the article using Jamal.
No manual copy, no outdated stale samples.
====

The sample project for this article contains only unit test files.
The class is `TestHiddenClassLoader`.
We have the source code for the hidden class stored in a field variable.

[source,java]
----
 1.     private static final String CODE1 = """
 2.             package com.javax0.blog.hiddenclasses;
 3.
 4.             public class MySpecialClass implements TestHiddenClassLoader.Hello {
 5.
 6.                 @Override
 7.                 public void hello() {
 8.                     System.out.println("Hello, from the hidden class.");
 9.                 }
10.             }
11.             """;

----

The interface is also inside the same class

[source,java]
----
1.     interface Hello {
2.         void hello();
3.     }

----

The following code is from one of the unit tests:

[source,java]
----
1.         final var byteCode = Compiler.java().from(CODE1).compile().get();
2.         final var lookup = MethodHandles.lookup();
3.         final var classLookup = lookup.defineHiddenClass(byteCode, true);
4.         final var helloClass = (Class<Hello>) classLookup.lookupClass();
5.
6.         final var hello = helloClass.getConstructor().newInstance();
7.         hello.hello();

----

In this code we use the link:https://github.com/sourcebuddy/sourcebuddy[SourceBuddy] library to compile the Java source to byte code.
The first line of the sample does that.
We use link:https://github.com/sourcebuddy/sourcebuddy[SourceBuddy] version 2.0.0.

To load the compiled byte code as a hidden class we need a lookup object.
This object is created on the second line.
The lookup object is used on the third and on the fourth line to load the class hidden.
Line 3 defines the class loading it into the JVM.
The second argument, `true` initializes the class.
That is when the `static{}` blocks execute.
The last line invokes the interface defined method `hello()`.

Now the local variable `hello` is an instance of an object, which is a hidden class.
What is the name, simple name and canonical name of a hidden class.
Let's print it out.

[source,java]
----
1.         System.out.println(hello.getClass());
2.         System.out.println(hello.getClass().getSimpleName());
3.         System.out.println(hello.getClass().getName());
4.         System.out.println(hello.getClass().getCanonicalName());

----


[%collapsible,title=Output Disclaimer, sidebar]
====
[sidebar]
The output in the unit tests is redirected calling `System.setOut()`.
The output is collected to a file and then this file is included calling `include [verbatim]` Jamal macro into the article.
====

[source,text]
----
Hello, from the hidden class.
class com.javax0.blog.hiddenclasses.MySpecialClass/0x000000080119c000
MySpecialClass/0x000000080119c000
com.javax0.blog.hiddenclasses.MySpecialClass/0x000000080119c000
null

----

You can see the output from calling `hello()` and then the name as printed from the implicit `toString()` from the class object, the simple name, the name and in the last line the canonical name.
This last one is the interesting as it is `null` showing that there is no name of the class.
It is hidden.



== 5. Creating hidden classes the easy way
